event_keywords = [
 "Participatory",
 "music jam sessions",
 "dancing",
 "theater",
 "Womens History",
 "Arts & Crafts",
 "Festival/fair",
 "Hike/Exercise",
 "Run or Walk",	
 "Virtual Event",
 "Santa Claus",
 "Outdoors Event",
 "Tour",
 "Craft sale / bazaar",
 "Farmers market",
 "Celebration",
 "Santa Claus",
 "Pioneer Day",
 "Community service / community activism",
 "Animals",
 "Games",
 "Nature",
 "Celebration",
 "Parade",
 "Christmas event",
 "Performance",
 "Class",
 "Food event",
 "Annual event",
 "Tasting event",
 "Story time",
 "reading",
 "Trunk-or-Treat / Halloween alternative",
 "Books / Reading / Stories",
 "Nature",
 "Animals",
 "Exhibit",
 "Family Night",
 "Tour",
 "Fireworks",
 "Parade",
 "Concert",
 "Festival/fair",
 "Outdoors Event",
 "Contest",
 "Hike/Exercise",
 "Performance",
 "Health/Physical Fitness",
 "Open House",
 "Parents night out",
 "Special deal",
 "Food event",
 "Audition",
 "Tournament",
 "After school / wraparound program",
 "Class",
 "Extracurricular",
 "Puppet Show",
 "Lecture/Demonstration",
 "Lesson",
 "Concert",
 "Family Night",
 "Party",
 "'Registration period'",
 "Lesson",	
 "Fireworks",
 "Camp",
 "Dance Performance",
 "Exhibit",
 "Fundraiser",
 "Drama/Musical Theater Performance",
 "Arts & Craft",
 "Health/Physical Fitness",
 "Food festival",
 "barbecue",
 "food truck rodeo"
 "winery celebration",
 "Pancake Breakfast",	
 "Parents night out",	
 "Author visit/Book signing",
 "Magic Show",
 "Sports Game/Match",
 "Community service",
 "Community activism",
 "Movie",
 "Extracurricular",
 "Books / Reading / Stories",
 "Author visit/Book signing",
 "Fundraiser",
 "Story teller",
 "Party",
 "Meeting (club or group)",
 "Lecture/Demonstration",
 "Puppet Show",
 "Tasting event",
 "breakfast",
 "brunch",
 "lunch",
 "dinner",
 "Fish Fry",
 "Giveaway",
 "Farmers market",
 "Story teller",
 "Food festival",
 "Consignment",
 "garage sale",
 "Dance Performance",
 "Special deal",
 "Story time - reading",
 "Tournament",
 "Games",
 "Rodeo",
 "Contest",
 "Open House",
 "School Tours",
 "Movie",
 "Giveaway",
 "Eclipse event",
 "Astronomy",
 "Star Party",
 "Egg hunt",
 "Sports Game/Match",
 "Virtual Event - online",
 "Consignment",
 "Family Game Night",
 "Magic Show",
 "After school / wraparound program",
 "Scouting/4-H event",
 "Easter meal",	
 "Egg hunt",
 "Religious celebration",
 "School Tours",
 "Family Game Night",
 "Maple syrup / sugar",
 "Scouting/4-H event",
 "Eclipse event",
 "Pancake Breakfast",
 "Lunar New Year",
 "Pokemon Go",
 "Registration period",
 "Drive-Thru / Drive-In / Drive-Up",
 "Star show / Nature film",
 "Research study",
 "Live Nativity",
 "Rodeo",
 "Research study",
 "Lunar New Year",
 "Christmas event",
 "Holiday Lights",
 "COVID-19 reopening event",
 ]