event_keywords = [
    "Participatory (e.g. music jam sessions, theater)",
    "Dancing"
    "Drama/Musical Theater Performance",
    "Women's History",
    "Arts & Crafts",
    "Festival/fair",
    "Festival",
    "Fair",
    "Hike/Exercise",
    "Exercise",
    "Run or Walk",
    "Virtual Event - online",
    "Not in person",
    "Santa Claus",
    "Outdoors Event",
    "Tour",
    "Craft sale / bazaar",
    "Farmer’s market",
    "Celebration",
    "Pioneer Day",
    "Community service / community activism",
    "Animals",
    "Games",
    "Nature",
    "Parade",
    "Christmas event",
    "Performance",
    "Class",
    "Food event",
    "Annual event",
    "Tasting event for food / beverage",
    "Story time - reading",
    "Trunk-or-Treat / Halloween alternative",
    "Books / Reading / Stories",
    "Stories",
    "Exhibit",
    "Family Night",
    "Fireworks",
    "Concert",
    "Contest",
    "Health/Physical Fitness",
    "Open House",
    "Parent's night out",
    "Special deal",
    "Audition",
    "Tournament",
    "After school / wraparound program",
    "Extracurricular",
    "Puppet Show",
    "Lecture/Demonstration",
    "Demonstration",
    "Lesson",
    "Camp - school break or summer",
    "Party",
    "Registration period",
    "Fundraiser",
    "Food festival (barbecue, food truck rodeo, winery celebration, etc)",
    "Pancake Breakfast",
    "Author visit/Book signing",
    "Magic Show",
    "Sports Game/Match",
    "Movie",
    "Story teller",
    "Meeting (club or group)",
    "Easter meal (breakfast, brunch, lunch, dinner)",
    "Breakfast",
    "Brunch",
    "Lunch",
    "Dinner",
    "Fish Fry",
    "Consignment, tag, or garage sale",
    "Garage sale",
    "School Tours",
    "Eclipse event",
    "Astronomy or Star Party",
    "Egg hunt",
    "Scouting/4-H event",
    "Religious celebration or observance",
    "Maple syrup / sugar",
    "Drive-Thru / Drive-In / Drive-Up",
    "Lunar New Year",
    "Star show / Nature film",
    "Pokemon Go",
    "Research study",
    "Live Nativity",
    "Holiday Lights",
    "COVID-19 reopening event"
]
